version: "3"
services:
  master:
    container_name: master
    build: ./master
    ports:
      - "18080:8080"
      - "5000:3000"
    volumes:
      - ./.ssh:/root/.ssh/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    tty: true

  #slave01:
    #container_name: slave01
    #build: ./slave01
    #ports:
      #- "10022:10022"
    #tty: true
    #environment:
      #- JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP6Kzew18mVSlb5WuwuofqFB2gCVRB6POMIWjBG9zwjrCE+vvXXD855zLVQjthshQLpZY4+yRVwZuo6LJvbeA+tH+D879EEyzoOrcU9G3SqyXaYCzCy0oXaYkcyd/n3v8hcCQ5PqvdVmFP5iWdmYKT2B7Q2JDzj1tu/I+2l170/3INUnGweYnSlCuRUbP2OiNiWRYDv7qn5vsE2WgFyAoOAJG8cvl+OMljK6HNjWQ2JNfHywo6srgP+T2eq0bynVRSpH255N3Xd6BpgK5GvfU0JVN/RxtzSAlEzM7kLlVG+L16b0MmYLMnkOeirj/kGY/HTFPTnPNtE3b1+U9+GBPr
